[phases.setup]
nixPkgs = ["go_1_24", "nodejs-20_x"]

[phases.install]
cmds = [
  "go mod download",
  "cd yjs-server && npm install"
]

[phases.build]
cmds = [
  "go build -o server ./cmd/server"
]

[start]
cmd = "./server"

